version: '3.5'

services:
  db_users: 
    container_name: db_users
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:15.2-alpine
    volumes: 
      -  db_users:/var/lib/postgresql/data